(* =========================================== *)
(* AUTEUR: Florian Legendre                    *)
(* OBJECTIF DE CE MODULE: Être le programme    *)
(* final qui sera compilé en un exécutable.    *)
(* Il est basé sur le travail produit dans les *)
(* deux autres .ml de ce dossier.              *)
(* =========================================== *)
